feelings/feelings/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

from django.views.generic import TemplateView

from rest_framework_jwt.views import obtain_jwt_token

from thoughts import urls as thought_urls
from users import urls as user_urls
from groups import urls as group_urls

from users import routers as user_routers
from thoughts import routers as thought_routers

from thoughts.viewsets import ConditionsView

api_urlpatterns = [
    url(r'', include(user_routers.router.urls)),
    url(r'', include(thought_routers.router.urls)),
]

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include(user_urls, namespace='users')),
    url(r'^thoughts/', include(thought_urls, namespace='thoughts')),
    url(r'^groups/', include(group_urls, namespace='groups')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^api/', include(api_urlpatterns)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^api/conditions', ConditionsView.as_view()),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

feelings/users/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
   url(r'^dashboard/$', views.Dashboard.as_view(), name='dashboard'),
   url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
   url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
   url('^', include('django.contrib.auth.urls')),
]

feelings/templates/index.html
{% extends "layout.html" %}

{% block content %}
<!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>Feelings!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>
<div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>
</div>
{% endblock %}

feelings/templates/layout.html
{% load static from staticfiles %}
{% load group_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>{% block title %}Feelings{% endblock %}</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  {% block css %}{% endblock %}
  <link rel="stylesheet" href="{% static 'css/feelings.css' %}">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">Feelings</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-left">
                {% if request.user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Companies {% invites_dot 'company' %}<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            {% for company in user.companies.all %}
                                <li><a href="{% url 'groups:companies:detail' slug=company.slug %}">{{ company.name }}</a></li>
                            {% endfor %}
                            <li role="separator" class="divider"></li>
                            <li>
                                <a href="{% url 'groups:companies:invites' %}">Invitations {% invites_badge 'company' %}</a>
                                <a href="{% url 'groups:companies:create' %}">Create New</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Families {% invites_dot 'family' %}<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            {% for family in user.families.all %}
                                <li><a href="{% url 'groups:families:detail' slug=family.slug %}">{{ family.name }}</a></li>
                            {% endfor %}
                            <li role="separator" class="divider"></li>
                            <li>
                                <a href="{% url 'groups:families:invites' %}">Invitations {% invites_badge 'family' %}</a>
                                <a href="{% url 'groups:families:create' %}">Create New</a>
                            </li>
                        </ul>
                    </li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
            {% if not user.is_authenticated %}
                <li><a href="{% url 'users:login' %}">Login</a></li>
                <li><a href="{% url 'users:signup' %}">Sign up</a></li>
            {% else %}
                <li><a href="{% url 'users:dashboard' %}">Dashboard</a></li>
                <li><a href="{% url 'users:logout' %}">Logout</a></li>
            {% endif %}
            </ul>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    {% block content %}{% endblock %}

    <div class="container">
     <hr>

      <footer>
        <p>&copy; 2016 Company, Inc.</p>
      </footer>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {% block js %}{% endblock %}
</body>
</html>